### ISSUE TITLE
Users could be a members of multiple communities

### ISSUE THREAD

**Issue by dsblank** [dsblank/activitypub#1]
Consider a babysitting community at a local area or school. How could the user ID be members of many nodes?

**Comment by dsblank** [comment]
This is an ActivityPub question best worked on at a higher level.

**Comment by autogestion** [comment]
This issue could be raised on litepub spec discussion

**Comment by dsblank** [comment]
This was one of the original questions I had about identity in the AP Federation. I think it deserves a standard of its own. I've joined the [W3C Social Web Incubator Community Group](https://www.w3.org/wiki/SocialCG). By the way, anyone can join: https://www.w3.org/community/socialcg/participants
