### ISSUE TITLE
Support for Django/SQLite3

### ISSUE THREAD

**Issue by ghost** [dsblank/activitypub#3]
A suggestion. I am already working on such an implementation, however I still think submitting an issue report is best practice

**Comment by dsblank** [comment]
Thanks, and cool!

**Comment by rigelk** [comment]
@gutfuckllc is there any way for me to help on that one? If you have a repo where this could be worked on, I'd gladly give you a hand.

**Comment by dsblank** [comment]
@gutfuckllc any progress on your project? @rigelk offered some help.
