### ISSUE TITLE
undeclared dependency on jinja2

### ISSUE THREAD

**Issue by marnanel** [dsblank/activitypub#4]

**Comment by dsblank** [comment]
Thanks for reporting! Are you able to use this project for something useful?

**Comment by marnanel** [comment]
Not just at present, but I will probably be soon. I'm building a Django library for ActivityPub and this will be useful for testing.

**Comment by dsblank** [comment]
Ok, thanks for the info. I've updated requirements.txt and setup.py to add 'jinja2' as a dependency.
